{
 "title": "Overview",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Phase", "label": "Phase", "query": "ALL, A, B, C" }
  ]
 },
 "panels": [
  { "title": "Actual values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Phase A", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 } },
  {
   "title": "Phase B",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"1_power\") FROM \"two_years\".\"meter\""
    }
   ]
  },
  {
   "title": "Phase C",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"2_power\") FROM \"two_years\".\"meter\" "
    }
   ]
  },
  {
   "title": "All Phases",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter",
     "query": "SELECT last(\"0_power\") + last(\"1_power\") + last(\"2_power\") AS Total  FROM two_years.meter",
     "select": [
      [
       { "params": [ "0_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter",
     "query": "SELECT last(\"total_P_AC\") + last(\"hms-1800_total_P_AC\") FROM \"two_years\".\"pv\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "0_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Yield Day",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter",
     "query": "SELECT last(\"total_YieldDay\") + last(\"hms-1800_total_YieldDay\") FROM \"two_years\".\"pv\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "0_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Yield Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter",
     "query": "SELECT last(\"total_YieldTotal\") + last(\"hms-1800_total_YieldTotal\") FROM \"two_years\".\"pv\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "0_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter",
     "query": "SELECT (last(\"0_total\")+ last(\"1_total\") + last(\"2_total\")  ) as total FROM \"two_years\".\"meter\" ",
     "select": [
      [
       { "params": [ "0_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "1500 Yield Day",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter",
     "query": "SELECT last(\"hm-1500_total_YieldDay\") FROM \"two_years\".\"pv\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "0_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "1500 Yield Tot",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter",
     "query": "SELECT last(\"hm-1500_total_YieldTotal\") FROM \"two_years\".\"pv\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "0_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT (integral(\"TOTAL\"))/3600 FROM \"ten_years\".\"tenminwise\" WHERE time >now()-3d GROUP BY time(1d)"
    }
   ]
  },
  {
   "title": "1800 Yield Day",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter",
     "query": "SELECT last(\"hms-1800_total_YieldDay\") FROM \"two_years\".\"pv\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "0_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "1800 Yield Tot",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter",
     "query": "SELECT last(\"hms-1800_total_YieldTotal\") FROM \"two_years\".\"pv\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "0_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT mean(\"0_power\") AS A , mean(\"1_power\") AS B, mean(\"2_power\") AS C,  mean(\"0_power\") + mean(\"1_power\") + mean(\"2_power\") AS TOTAL FROM \"two_years\".\"meter\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Production",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "SELECT mean(\"hms-1800_total_P_AC\") as HMS18 , mean(\"total_P_AC\") as HM15 FROM \"two_years\".\"pv\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "10 minwise",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pv",
     "query": "SELECT mean(\"H18_TOTAL\") AS HMS18, mean(\"PV_TOTAL\") AS HM15, mean(\"TOTAL\") AS TOTAL  FROM \"ten_years\".\"tenminwise\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "hm-1500_total_P_AC" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hourly (mean)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pv",
     "query": "SELECT mean(\"H18_TOTAL\") AS HMS18, mean(\"PV_TOTAL\") AS HM15, mean(\"TOTAL\") AS TOTAL  FROM \"ten_years\".\"hourly\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "hm-1500_total_P_AC" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Per Day Overview",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pv",
     "query": "SELECT PV_YIELD_DAY, TOTAL  FROM \"ten_years\".\"daily\" WHERE time > now()-7d",
     "select": [
      [
       { "params": [ "hm-1500_total_P_AC" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Per Week Overview",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pv",
     "query": "SELECT mean_PV_YIELD_DAY, mean_TOTAL  FROM \"ten_years\".\"weekly\" WHERE time > now()-5w",
     "select": [
      [
       { "params": [ "hm-1500_total_P_AC" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       }
      ]
     ]
    }
   ]
  }
 ]
}